package casemgmt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Diagnose implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Diagnose")
   private java.lang.String diagnose;
   @org.kie.api.definition.type.Label(value = "Date")
   private java.util.Date date;
   @org.kie.api.definition.type.Label(value = "Explanation")
   private java.lang.String explanation;

   public Diagnose()
   {
   }

   public java.lang.String getDiagnose()
   {
      return this.diagnose;
   }

   public void setDiagnose(java.lang.String diagnose)
   {
      this.diagnose = diagnose;
   }

   public java.util.Date getDate()
   {
      return this.date;
   }

   public void setDate(java.util.Date date)
   {
      this.date = date;
   }

   public java.lang.String getExplanation()
   {
      return this.explanation;
   }

   public void setExplanation(java.lang.String explanation)
   {
      this.explanation = explanation;
   }

   public Diagnose(java.lang.String diagnose, java.util.Date date,
         java.lang.String explanation)
   {
      this.diagnose = diagnose;
      this.date = date;
      this.explanation = explanation;
   }

}