package casemgmt;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Patient implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Age")
   private java.lang.Integer age;
   @org.kie.api.definition.type.Label("SSN")
   private java.lang.String SSN;

   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;

   public Patient()
   {
   }

   public java.lang.Integer getAge()
   {
      return this.age;
   }

   public void setAge(java.lang.Integer age)
   {
      this.age = age;
   }

   public java.lang.String getSSN()
   {
      return this.SSN;
   }

   public void setSSN(java.lang.String SSN)
   {
      this.SSN = SSN;
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public Patient(java.lang.Integer age, java.lang.String SSN,
         java.lang.String name)
   {
      this.age = age;
      this.SSN = SSN;
      this.name = name;
   }

}